apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  template:
    spec:
      containers:
      - name: oauth2-proxy
        args: 
        # name of this cookie is also referenced in Ingresses (cookie split issue)
        - --cookie-name=auth
        - --cookie-refresh=1h
        - --cookie-secure=true
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --oidc-issuer-url=https://keycloak.$(DOMAIN)/auth/realms/KubePlatform
        - --pass-access-token=true
        - --provider=oidc
        - --set-xauthrequest=true
        - --tls-cert=
        - --upstream=file:///dev/null
        # remove for prod cluster issuer
        - --ssl-insecure-skip-verify=true
        envFrom:
        - configMapRef:
            name: kubeplatform-config